# Generated by Django 5.1.2 on 2024-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='description',
        ),
        migrations.AddField(
            model_name='blogsection',
            name='blog_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='blog_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='t_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
