# Generated by Django 5.1.2 on 2024-11-10 18:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='blog_text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='blog_text_2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
