# Generated by Django 5.1.2 on 2024-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogsection_feature_blogwindow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='home.category'),
        ),
    ]
