# Generated by Django 5.1.2 on 2024-11-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
