# Generated by Django 5.1.2 on 2024-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_banner_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
