# Generated by Django 5.1.2 on 2024-11-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
